
# tap repositories and their packages

tap homebrew/core
brew afflib
brew apktool
brew autoconf
brew automake
brew autopsy
brew bash
brew bash-completion
brew bison
brew boost
brew bulk_extractor
brew cfr-decompiler
brew coreutils
brew ddrescue
brew dex2jar
brew flex
brew fontconfig
brew foremost
brew freetype
brew gcc
brew gd
brew gdbm
brew gettext
brew ghostscript
brew git
brew glib
brew gmp
brew gnutls
brew gradle
brew graphviz
brew gts
brew hashcat
brew icu4c
brew isl
brew jadx
brew jansson
brew jasper
brew jpeg
brew jq
brew libevent
brew libewf
brew libffi
brew libidn2
brew libimobiledevice
brew libmagic
brew libmpc
brew libplist
brew libpng
brew libpq
brew libssh
brew libssh2
brew libtasn1
brew libtiff
brew libtool
brew libunistring
brew libusb
brew libusbmuxd
brew libxml2
brew lzo
brew mas
brew mpfr
brew ncurses
brew netpbm
brew nettle
brew numpy
brew oniguruma
brew openblas
brew openssl@1.1
brew p11-kit
brew p7zip
brew pcre
brew pcre2
brew pixman
brew pkg-config
brew protobuf
brew pyenv
brew pyenv-virtualenvwrapper
brew python
brew qemu
brew readline
brew sbt
brew scala
brew sleuthkit
brew sqlcipher
brew sqlite
brew sshfs
brew trash
brew ucl
brew unbound
brew upx
brew vde
brew volatility
brew webp
brew wxmac
brew wxpython
brew xz
brew yara

tap homebrew/cask-drivers
cask synologyassistant

tap homebrew/cask-fonts
cask font-calligraffitti
cask font-myrica
cask font-noto-sans
cask font-open-sans
cask font-raleway
cask font-roboto

tap homebrew/cask-versions
cask adoptopenjdk8
cask java11

tap homebrew/cask
cask 010-editor
cask adobe-acrobat-reader
cask adobe-air
cask android-studio
cask appcleaner
cask aquaskk
cask arduino
cask balenaetcher
cask checkra1n
cask cmake
cask cutter
cask db-browser-for-sqlite
cask docker
cask dotnet-sdk
cask doxygen
cask firefox
cask fork
cask genymotion
cask ghidra
cask google-backup-and-sync
cask google-chrome
cask gpg-suite
cask idafree
cask iexplorer
cask ifunbox
cask impactor
cask intellij-idea-ce
cask iterm2
cask kindle
cask mactex
cask mendeley-desktop
cask mono-mdk
cask musescore
cask osxfuse
cask powershell
cask realm-studio
cask rsyncosx
cask slack
cask veracrypt
cask virtualbox
cask virtualbox-extension-pack
cask visual-studio
cask visual-studio-code
cask vlc
cask vmware-fusion
cask wireshark
cask xquartz

tap rcmdnk/file
brew brew-file

# App Store applications
appstore 1037126344 Apple Configurator 2 (2.11.1)
appstore 409183694 Keynote (9.2.1)
appstore 539883307 LINE (5.21.3)
appstore 409203825 Numbers (6.2.1)
appstore 409201541 Pages (8.2.1)
appstore 497799835 Xcode (11.3.1)
