
# tap repositories and their packages

tap homebrew/core
brew afflib
brew ant
brew autoconf
brew automake
brew autopsy
brew bash
brew bash-completion
brew bdw-gc
brew bison
brew boost
brew bulk_extractor
brew c-ares
brew cairo
brew carthage
brew cfr-decompiler
brew cmake
brew coreutils
brew ddrescue
brew dex2jar
brew flex
brew fontconfig
brew foremost
brew freetype
brew fribidi
brew gcc
brew gd
brew gdbm
brew gdk-pixbuf
brew gettext
brew ghostscript
brew git
brew glib
brew gmp
brew gnutls
brew gobject-introspection
brew gradle
brew graphite2
brew graphviz
brew gts
brew guile
brew harfbuzz
brew hashcat
brew icu4c
brew ideviceinstaller
brew isl
brew jadx
brew jansson
brew jasper
brew jbig2dec
brew jemalloc
brew jpeg
brew jq
brew kaitai-struct-compiler
brew krb5
brew ldid
brew libev
brew libevent
brew libewf
brew libffi
brew libgcrypt
brew libgpg-error
brew libidn
brew libidn2
brew libimobiledevice
brew libirecovery
brew libmagic
brew libmaxminddb
brew libmpc
brew libplist
brew libpng
brew libpq
brew libpthread-stubs
brew librsvg
brew libslirp
brew libsmi
brew libssh
brew libssh2
brew libtasn1
brew libtiff
brew libtool
brew libunistring
brew libusb
brew libusbmuxd
brew libx11
brew libxau
brew libxcb
brew libxdmcp
brew libxext
brew libxml2
brew libxrender
brew libzip
brew little-cms2
brew llvm
brew lua
brew lzo
brew m4
brew make
brew mas
brew meson
brew mpdecimal
brew mpfr
brew ncurses
brew netpbm
brew nettle
brew nghttp2
brew ninja
brew nodebrew
brew oniguruma
brew openblas
brew openjdk
brew openjdk@11
brew openjpeg
brew openssl@1.1
brew p11-kit
brew p7zip
brew pango
brew pcre
brew pcre2
brew pixman
brew pkg-config
brew protobuf
brew protobuf-c
brew pyenv
brew pyenv-virtualenv
brew pyenv-virtualenvwrapper
brew python@3.9
brew qemu
brew radare2
brew readline
brew sbt
brew scala
brew six
brew sleuthkit
brew smartmontools
brew snappy
brew sphinx-doc
brew sqlcipher
brew sqlite
brew tcl-tk
brew testdisk
brew trash
brew tree
brew ucl
brew unbound
brew upx
brew vde
brew webp
brew wxmac
brew xorgproto
brew xz
brew yara
brew zsh
brew zsh-autosuggestions
brew zsh-completions
brew zsh-syntax-highlighting
brew zstd

tap homebrew/cask-drivers
cask eizo-colornavigator
cask hhkb-keymap-tool
cask hhkb-pro-driver
cask logitech-options
cask synologyassistant

tap homebrew/cask-fonts
cask font-calligraffitti
cask font-myrica
cask font-noto-sans

tap homebrew/cask-versions
cask mono-mdk-for-visual-studio

tap homebrew/cask
cask 010-editor
cask adobe-acrobat-reader
cask adobe-air
cask altserver
cask android-studio
cask appcleaner
cask aquaskk
cask arduino
cask balenaetcher
cask checkra1n
cask cmake
cask cutter
cask db-browser-for-sqlite
cask discord
cask docker
cask dotnet-sdk
cask doxygen
cask firefox
cask fork
cask geekbench
cask genymotion
cask ghidra
cask google-backup-and-sync
cask google-chrome
cask gpg-suite
cask iexplorer
cask ifunbox
cask impactor
cask intellij-idea-ce
cask ios-app-signer
cask iterm2
cask kindle
cask macfuse
cask mactex
cask mendeley
cask microsoft-auto-update
cask microsoft-office
cask mongodb-realm-studio
cask musescore
cask parallels
cask powershell
cask rsyncosx
cask slack
cask veracrypt
cask virtualbox
cask virtualbox-extension-pack
cask visual-studio
cask visual-studio-code
cask vlc
cask vmware-fusion
cask wireshark
cask xquartz
cask zoom

tap adoptopenjdk/openjdk
cask adoptopenjdk11

tap rcmdnk/file
brew brew-file

# App Store applications
appstore 1037126344  Apple Configurator 2      (2.14)
appstore 640199958   Developer                 (9.2)
appstore 682658836   GarageBand                (10.4.3)
appstore 408981434   iMovie                    (10.2.3)
appstore 409183694   Keynote                   (11.1)
appstore 539883307   LINE                      (6.7.3)
appstore 1295203466  Microsoft Remote Desktop  (10.6.6)
appstore 409203825   Numbers                   (11.1)
appstore 409201541   Pages                     (11.1)
appstore 1429033973  RunCat                    (9.1)
appstore 497799835   Xcode                     (12.5)
